#   Travis-ci.org configuration file for ABRAID-MP
#   Copyright (c) 2014 University of Oxford
services:
  - postgresql
before_script:
  - dpkg -l | grep -i post
  - sudo apt-get purge libgeos++-dev
  - chmod +x *.sh
script:
  - ./test.sh
